# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/etudiant/projects/ECP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/etudiant/projects/ECP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etudiant/projects/ECP/CMakeFiles /home/etudiant/projects/ECP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/etudiant/projects/ECP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ecp

# Build rule for target.
ecp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ecp
.PHONY : ecp

# fast build rule for target.
ecp/fast:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/build
.PHONY : ecp/fast

basictabusearch.o: basictabusearch.cpp.o
.PHONY : basictabusearch.o

# target to build an object file
basictabusearch.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/basictabusearch.cpp.o
.PHONY : basictabusearch.cpp.o

basictabusearch.i: basictabusearch.cpp.i
.PHONY : basictabusearch.i

# target to preprocess a source file
basictabusearch.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/basictabusearch.cpp.i
.PHONY : basictabusearch.cpp.i

basictabusearch.s: basictabusearch.cpp.s
.PHONY : basictabusearch.s

# target to generate assembly for a file
basictabusearch.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/basictabusearch.cpp.s
.PHONY : basictabusearch.cpp.s

binarysearch.o: binarysearch.cpp.o
.PHONY : binarysearch.o

# target to build an object file
binarysearch.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/binarysearch.cpp.o
.PHONY : binarysearch.cpp.o

binarysearch.i: binarysearch.cpp.i
.PHONY : binarysearch.i

# target to preprocess a source file
binarysearch.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/binarysearch.cpp.i
.PHONY : binarysearch.cpp.i

binarysearch.s: binarysearch.cpp.s
.PHONY : binarysearch.s

# target to generate assembly for a file
binarysearch.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/binarysearch.cpp.s
.PHONY : binarysearch.cpp.s

coloration.o: coloration.cpp.o
.PHONY : coloration.o

# target to build an object file
coloration.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/coloration.cpp.o
.PHONY : coloration.cpp.o

coloration.i: coloration.cpp.i
.PHONY : coloration.i

# target to preprocess a source file
coloration.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/coloration.cpp.i
.PHONY : coloration.cpp.i

coloration.s: coloration.cpp.s
.PHONY : coloration.s

# target to generate assembly for a file
coloration.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/coloration.cpp.s
.PHONY : coloration.cpp.s

graphe.o: graphe.cpp.o
.PHONY : graphe.o

# target to build an object file
graphe.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/graphe.cpp.o
.PHONY : graphe.cpp.o

graphe.i: graphe.cpp.i
.PHONY : graphe.i

# target to preprocess a source file
graphe.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/graphe.cpp.i
.PHONY : graphe.cpp.i

graphe.s: graphe.cpp.s
.PHONY : graphe.s

# target to generate assembly for a file
graphe.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/graphe.cpp.s
.PHONY : graphe.cpp.s

iteratedtabusearch.o: iteratedtabusearch.cpp.o
.PHONY : iteratedtabusearch.o

# target to build an object file
iteratedtabusearch.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/iteratedtabusearch.cpp.o
.PHONY : iteratedtabusearch.cpp.o

iteratedtabusearch.i: iteratedtabusearch.cpp.i
.PHONY : iteratedtabusearch.i

# target to preprocess a source file
iteratedtabusearch.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/iteratedtabusearch.cpp.i
.PHONY : iteratedtabusearch.cpp.i

iteratedtabusearch.s: iteratedtabusearch.cpp.s
.PHONY : iteratedtabusearch.s

# target to generate assembly for a file
iteratedtabusearch.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/iteratedtabusearch.cpp.s
.PHONY : iteratedtabusearch.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/main.cpp.s
.PHONY : main.cpp.s

onemove.o: onemove.cpp.o
.PHONY : onemove.o

# target to build an object file
onemove.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/onemove.cpp.o
.PHONY : onemove.cpp.o

onemove.i: onemove.cpp.i
.PHONY : onemove.i

# target to preprocess a source file
onemove.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/onemove.cpp.i
.PHONY : onemove.cpp.i

onemove.s: onemove.cpp.s
.PHONY : onemove.s

# target to generate assembly for a file
onemove.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/onemove.cpp.s
.PHONY : onemove.cpp.s

swap.o: swap.cpp.o
.PHONY : swap.o

# target to build an object file
swap.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/swap.cpp.o
.PHONY : swap.cpp.o

swap.i: swap.cpp.i
.PHONY : swap.i

# target to preprocess a source file
swap.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/swap.cpp.i
.PHONY : swap.cpp.i

swap.s: swap.cpp.s
.PHONY : swap.s

# target to generate assembly for a file
swap.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/swap.cpp.s
.PHONY : swap.cpp.s

voisin.o: voisin.cpp.o
.PHONY : voisin.o

# target to build an object file
voisin.cpp.o:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/voisin.cpp.o
.PHONY : voisin.cpp.o

voisin.i: voisin.cpp.i
.PHONY : voisin.i

# target to preprocess a source file
voisin.cpp.i:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/voisin.cpp.i
.PHONY : voisin.cpp.i

voisin.s: voisin.cpp.s
.PHONY : voisin.s

# target to generate assembly for a file
voisin.cpp.s:
	$(MAKE) -f CMakeFiles/ecp.dir/build.make CMakeFiles/ecp.dir/voisin.cpp.s
.PHONY : voisin.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ecp"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... basictabusearch.o"
	@echo "... basictabusearch.i"
	@echo "... basictabusearch.s"
	@echo "... binarysearch.o"
	@echo "... binarysearch.i"
	@echo "... binarysearch.s"
	@echo "... coloration.o"
	@echo "... coloration.i"
	@echo "... coloration.s"
	@echo "... graphe.o"
	@echo "... graphe.i"
	@echo "... graphe.s"
	@echo "... iteratedtabusearch.o"
	@echo "... iteratedtabusearch.i"
	@echo "... iteratedtabusearch.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... onemove.o"
	@echo "... onemove.i"
	@echo "... onemove.s"
	@echo "... swap.o"
	@echo "... swap.i"
	@echo "... swap.s"
	@echo "... voisin.o"
	@echo "... voisin.i"
	@echo "... voisin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

